apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marge.fullname"  . }}-config
  labels:
    {{- include "marge.labels" . | nindent 4 }}
data:
  {{- if .Values.config }}
  marge-bot-config.yaml: {{ .Values.config | quote }}
  {{- end }}
