apiVersion: v1
kind: Secret
metadata:
  name: {{ include "marge.fullname"  . }}-secret
  labels:
    {{- include "marge.labels" . | nindent 4 }}
type: Opaque
data:
  gitlab-url: {{ .Values.secret.gitlabUrl | b64enc | quote }}
  ssh-key: {{ .Values.secret.sshKey | quote }}
  auth-token: {{ .Values.secret.authToken | b64enc | quote }}
